stages:
  - test
  - build

run_mayday_test:
  image: gcr.io/mist-ops/tests_base
  stage: test
  only:
    - triggers
  before_script:
    - echo $MAYDAY_SETTINGS | base64 -d > test_settings.py
    - export DISPLAY=:1.0
    - pip install -e .
  script:
    - python prepare_env.py -k --tags=alert,graph,ssh,celery,google_sso_signin,github_sso_signin misttests/legacy_gui/core/mayday/features
  artifacts:
    paths:
      - js_console.log
      - error*
      - test.mp4
    expire_in: 7 days
    when: always
